[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

```eof

* `command = "npx expo export -p web"` : C'est la commande que Netlify lancera pour transformer ton code en un site web statique.
* `publish = "dist"` : Indique que le résultat de la commande se trouvera dans un dossier nommé `dist`.
* La section `[[redirects]]` est **cruciale**. Elle garantit que si un utilisateur rafraîchit la page sur une URL comme `monsite.com/dashboard`, il ne verra pas une erreur 404.

---

### ## Étape 2 : Mettre votre projet sur GitHub

Netlify fonctionne mieux lorsqu'il est connecté à un dépôt Git (comme GitHub, GitLab ou Bitbucket).

1.  Assure-toi que tout ton code est bien sur GitHub.
2.  Pense à ajouter le fichier `netlify.toml` que tu viens de créer.
    ```bash
    git add netlify.toml
    git commit -m "Add Netlify configuration"
    git push
    ```

---

### ## Étape 3 : Créer et configurer le site sur Netlify

Maintenant, passons à l'interface de Netlify.

1.  **Connecte-toi** à ton compte Netlify (ou crées-en un, c'est gratuit).
2.  Sur ton tableau de bord, clique sur **"Add new site"** puis **"Import an existing project"**.
3.  **Connecte-toi à GitHub** (ou ton fournisseur Git) et autorise Netlify.
4.  **Choisis le dépôt** de ton application admin dans la liste.
5.  Netlify va lire ton fichier `netlify.toml` et devrait **automatiquement remplir les bons paramètres de build** :
    * **Build command** : `npx expo export -p web`
    * **Publish directory** : `dist`

    Si ce n'est pas le cas, remplis-les manuellement.

---

### ## Étape 4 : Ajouter les variables d'environnement (Très Important !) 🔒

N'envoie jamais tes clés d'API (comme celles de Firebase) sur GitHub. Tu dois les configurer directement dans Netlify pour qu'elles restent secrètes.

1.  Dans les paramètres de ton site sur Netlify, va dans **"Site settings"** > **"Build & deploy"** > **"Environment"**.
2.  Clique sur **"Edit variables"** et ajoute, une par une, toutes les clés secrètes dont ton application a besoin. Par exemple :
    * `FIREBASE_API_KEY` = `AIzaSy...`
    * `FIREBASE_AUTH_DOMAIN` = `votre-projet.firebaseapp.com`
    * `FIREBASE_PROJECT_ID` = `votre-projet`
    * etc.

Ces variables seront disponibles pour ton application pendant le processus de build.

---

### ## Étape 5 : Lancer le déploiement ! 🚀

Une fois la configuration terminée, clique sur **"Deploy site"**.

Netlify va récupérer ton code sur GitHub, installer les dépendances, lancer la commande de build `npx expo export -p web` et mettre en ligne le dossier `dist`.

Tu pourras suivre la progression en direct. Une fois terminé, tu auras une URL du type `nom-genere-aleatoirement.netlify.app` que tu pourras visiter. Tu pourras bien sûr changer ce nom dans les paramètres du site plus tard.

Et voilà ! Ton panel admin sera en ligne. ✨